Added test for sdx receipt
ONSdigital/ssdc-rm-acceptance-tests pull request #122
Opened 2022-09-01 09:01 UTC by ryangrundy7

# Motivation and Context

* [ ] [Context Index](/CODE_GUIDE.md#context-index) has been kept up to date

Added a test to check that the sdx-receipt functionality works

# What has changed

- Added sdx-receipt-adapter test
# How to test?

- Run against the docker-dev and terraform branches to check it works in cloud and local dev
# Links

[Trello](https://trello.com/c/BmXFriNQ/)
# Screenshots (if appropriate):

2022-09-01 15:18 UTC, davidmort approved these changes

2022-09-02 08:01 UTC, AdamHawtin commented on acceptance_tests/features/sdx_receipt.feature
> +    And an export file action rule has been created
SMS or email are a faster way of just getting a UAC for the case.

2022-09-02 08:07 UTC, AdamHawtin requested changes
Can speed up the scenario a bit.

Also, minor point r.e. the PR label 💅 I would consider adding new scenarios to be `feature` in the AT's rather than `patch` , maybe the README needs a couple of words on what we agree as the change levels here (we probably need that everywhere to be honest).

2022-09-07 07:07 UTC, liamtoozer approved these changes

2022-09-08 13:12 UTC, AdamHawtin approved these changes

2022-09-08 13:57 UTC, merged