621 Test EQ Flush
ONSdigital/ssdc-rm-acceptance-tests pull request #149
Opened 2023-01-06 10:55 UTC by AdamHawtin

# Motivation and Context

* [ ] [Context Index](/CODE_GUIDE.md#context-index) has been kept up to date

# What has changed

# How to test?

# Links

# Screenshots (if appropriate):

2023-01-13 15:29 UTC, davidmort requested changes
do we need to update the run_gke.sh script to use the `cloud_only` behave tag?

2023-01-16 07:58 UTC, AdamHawtin commented
@davidmort It shouldn't need it, that tag is only used to exclude scenarios when running locally so nothing running in the cloud should need to change.

2023-01-16 07:59 UTC, davidmort commented
> @davidmort It shouldn't need it, that tag is only used to exclude scenarios when running locally, so nothing running in the cloud should need to change.

fair enough, then all looks good to me 👍

2023-01-16 07:59 UTC, davidmort approved these changes

2023-01-17 13:53 UTC, LukeLoze1 approved these changes

2023-01-18 09:52 UTC, merged