Add new endpoint to sample load
ONSdigital/ssdc-rm-acceptance-tests pull request #28
Opened 2021-08-11 08:42 UTC by hbrace

# Motivation and Context

* [ ] [Context Index](/CODE_GUIDE.md#context-index) has been kept up to date
Sample load function updated to reflect new changes in support tool when loading sample.
# What has changed

Call to job creation endpoint added to sample load function.
# How to test?

Build support tool image using [branch of the same name.](https://github.com/ONSdigital/ssdc-rm-support-tool/pull/46) and run ATs, check no failures.
# Links

https://trello.com/c/wx7CEHqo/2594-massive-sample-file-upload-fails-due-to-jwt-token-expiry
# Screenshots (if appropriate):

2021-08-11 08:43 UTC, hbrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [Massive sample file upload fails due to JWT token expiry](https://trello.com/c/wx7CEHqo/2594-massive-sample-file-upload-fails-due-to-jwt-token-expiry)

2021-08-11 13:46 UTC, NickGrantONS approved these changes

2021-08-12 06:59 UTC, AdamHawtin commented on acceptance_tests/features/steps/sample_loading.py
> +    file_id = eval(response.text)
```suggestion
    file_id = response.json()
```
`response.json()` still works here, should be preferred to using `eval`.

2021-08-12 07:02 UTC, AdamHawtin requested changes
Got it passing locally, just one small change request, and I'm happy 👍

2021-08-12 07:33 UTC, AdamHawtin approved these changes

2021-08-12 07:34 UTC, merged