2510 uac by sms
ONSdigital/ssdc-rm-acceptance-tests pull request #32
Opened 2021-08-19 13:23 UTC by ryangrundy7

# Motivation and Context

* [x] [Context Index](/CODE_GUIDE.md#context-index) has been kept up to date
Adding new tests for the notify service sms fulfilments
# What has changed

- Adding new tests for the notify service sms fulfilments

# How to test?

- Run with other PRs on ticket
# Links

[Trello](Adding new tests for the notify service sms fulfilments)
# Screenshots (if appropriate):

2021-08-19 13:23 UTC, ryangrundy7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Prototype: Send a UAC by SMS by API (13)](https://trello.com/c/uQcwIQcQ/2510-prototype-send-a-uac-by-sms-by-api-13)

2021-08-19 15:27 UTC, NickGrantONS commented on CODE_GUIDE.md
> +| notify_id                 | Stores the ID of the sms template used for the notify service                                 |
```suggestion
| notify_template_id                 | Stores the ID of the sms template used for the notify service                                 |
```

2021-08-19 15:31 UTC, NickGrantONS commented on acceptance_tests/features/steps/print_file.py
> +        'notifyId': context.notify_id,
```suggestion
        'notifyTemplateId': context.notify_template_id,
```

2021-08-19 15:32 UTC, NickGrantONS commented on acceptance_tests/features/steps/print_file.py
> +    context.notify_id = str(uuid.uuid4())
```suggestion
    context.notify_template_id = str(uuid.uuid4())
```

2021-08-19 15:33 UTC, NickGrantONS commented on acceptance_tests/features/steps/sms_fulfilment.py
> +def _check_notify_api_called_with_correct_notify_id(phone_number, notify_id):
```suggestion
def _check_notify_api_called_with_correct_notify_template_id(phone_number, notify_id):
```

2021-08-19 15:33 UTC, NickGrantONS commented on acceptance_tests/features/steps/sms_fulfilment.py
> +    test_helper.assertEqual(response_json[0]["template_id"], notify_id, "Incorrect template Id")
```suggestion
    test_helper.assertEqual(response_json[0]["template_id"], notify_template_id, "Incorrect Gov Notify template Id")
```

2021-08-19 15:35 UTC, NickGrantONS commented on acceptance_tests/features/steps/sms_fulfilment.py
> +    _check_notify_api_called_with_correct_notify_id(context.phone_number, context.notify_id)
```suggestion
    _check_notify_api_called_with_correct_notify_template_id(context.phone_number, context.notify_template_id)
```

2021-08-19 15:36 UTC, NickGrantONS requested changes
See comments

2021-08-23 08:23 UTC, NickGrantONS approved these changes
ATs passing. Great work

2021-08-23 10:06 UTC, liamtoozer approved these changes
LGTM 👍  Tested locally

2021-08-23 13:28 UTC, merged