Fix for flakey ATs in GCP
ONSdigital/ssdc-rm-acceptance-tests pull request #39
Opened 2021-09-07 07:43 UTC by NickGrantONS

# Motivation and Context
The ATs fail very frequently on the step `UAC_UPDATE messages are emitted with active set to {active:boolean}`.
* [ ] [Context Index](/CODE_GUIDE.md#context-index) has been kept up to date

# What has changed
Put some retry code and other defensive coding, to try to improve the tests reliability.

# How to test?
It's an intermittent failure that only happens in GCP... so only time will tell if it's an improvement or not.

# Links
Trello: https://trello.com/c/0XbDXZ0q

2021-09-07 07:45 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [ATs are flakey in GCP/CI](https://trello.com/c/0XbDXZ0q/2754-ats-are-flakey-in-gcp-ci)

2021-09-07 14:21 UTC, hbrace approved these changes

2021-09-08 07:29 UTC, AdamHawtin approved these changes

2021-09-08 08:27 UTC, LukeLoze1 approved these changes

2021-09-08 09:08 UTC, AdamHawtin requested changes
Having dug a bit more into how the subscriber client behaves, I don't think this approach will help. I suspect the client is eagerly returning messages as soon as it sees _any_ on the subscription, so this change would end up splitting the messages over multiple failed attempts.

I've had a go at re-writing how we pull an expected number of messages in #42 which will hopefully allow the tests to instead wait for the full specified timeout duration for the expected number of messages to be pulled.

2021-09-08 09:40 UTC, NickGrantONS commented
@AdamHawtin has found a better way of doing this

2021-09-08 09:40 UTC, closed without merging