Exception manager retry
ONSdigital/ssdc-rm-acceptance-tests pull request #48
Opened 2021-09-14 10:05 UTC by LukeLoze1

# Motivation and Context
ATs were flakey.  Remove some more sleeps, use retry instead.  Add scenario specific email address for each message sent.

# How to test?
With exception manager from this ticket.  Should work with zero regression

# Links
https://trello.com/c/ahavO1oz/2753-acceptance-tests-flakiness-8

# Screenshots (if appropriate):

2021-09-16 13:15 UTC, NickGrantONS commented on acceptance_tests/features/exception_manager.feature
> +    When a bad invalid case message is put on the topic with email address "BadDeactivate"
```suggestion
    When a bad invalid case message is put on the topic with email address "BadInvalidCase"
```

2021-09-16 14:06 UTC, NickGrantONS requested changes
What was wrong with the existing `/skippedmessages` Exception Manger endpoint? that should be pretty easy to use, and saves us bloating the API

2021-09-17 09:04 UTC, NickGrantONS approved these changes
Looks good

2021-09-17 10:52 UTC, gavinleeedwards approved these changes

2021-09-17 10:59 UTC, merged