Add calls to case api to check presence of events
ONSdigital/ssdc-rm-acceptance-tests pull request #6
Opened 2021-06-30 13:32 UTC by hbrace

Why?
We want the tests to check case events are present
What?
Calls to case api added to a lot of tests, also new scenarios for telephone capture and respondent authenticated

The respondent authenticated message uses the same content as the survey launched message and it works as I can't find anything to say it should be different so if you think it should be let me know

How?
`make test`
Links?
https://trello.com/c/Q8yG9XgD/2397-case-api-acceptance-tests-5

2021-06-30 13:33 UTC, hbrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [Case API Acceptance tests (5)](https://trello.com/c/Q8yG9XgD/2397-case-api-acceptance-tests-5)

2021-07-01 07:10 UTC, NickGrantONS requested changes
Great work but unfortunately the sands have shifted under your feet and ATs are now failing because `PRINTED_PACK_CODE` events are present

2021-07-01 07:40 UTC, AdamHawtin commented on acceptance_tests/utilities/case_api_helper.py
> +    response = requests.get(f'{Config.CASE_API_CASE_URL}{case_id}?caseEvents=true').content.decode("utf-8")
needs a raise for status

2021-07-01 07:43 UTC, AdamHawtin commented on acceptance_tests/features/steps/telephone_capture.py
> +    response = requests.get(f'{Config.CASE_API_CASE_URL}{context.loaded_case_ids[0]}/telephone-capture')
Needs a raise for status

2021-07-01 07:50 UTC, AdamHawtin requested changes
A few small comments

2021-07-01 08:14 UTC, AdamHawtin commented on acceptance_tests/features/steps/receipt.py
> +def check_survey_launch_event_logging(context, expected_event_list):
Bad function name. This step also seems to be duplicated, I would suggest writing it once in an events step file

2021-07-01 08:15 UTC, AdamHawtin commented on acceptance_tests/features/steps/refusal.py
> +def check_survey_launch_event_logging(context, expected_event_list):
Bad function name. This step also seems to be duplicated, I would suggest writing it once in an events step file

2021-07-01 08:15 UTC, AdamHawtin commented on acceptance_tests/features/steps/respondent_authenticated.py
> +def check_survey_launch_event_logging(context, expected_event_list):
Bad function name. This step also seems to be duplicated, I would suggest writing it once in an events step file

2021-07-01 08:15 UTC, AdamHawtin commented on acceptance_tests/features/steps/survey_launched.py
> +def check_survey_launch_event_logging(context, expected_event_list):
This step also seems to be duplicated, I would suggest writing it once in an events step file

2021-07-01 09:12 UTC, NickGrantONS approved these changes
ATs passing. Great work 👍

2021-07-01 12:20 UTC, AdamHawtin approved these changes
All passing locally, good stuff 👍

2021-07-01 12:24 UTC, merged

2021-07-01 12:32 UTC, LukeLoze1 requested changes

2021-07-01 12:32 UTC, LukeLoze1 commented on acceptance_tests/features/steps/events.py
> +@step("the events logged for the case requesting telephone capture are {expected_event_list}")
I prefer a single step name, something like 'events logged against first emitted case are {expected_event_list}

Feels less misleading to me?

2021-07-01 12:32 UTC, LukeLoze1 commented on acceptance_tests/features/steps/events.py
> +@step("the events logged for the case requesting telephone capture are {expected_event_list}")
This could be left to refactoring work.

2021-07-01 12:32 UTC, LukeLoze1 commented on acceptance_tests/features/telephone_capture.feature
> +    When there is a request for telephone capture of a case
I'd prefer this to be one step of something like:
A request for telephone capture of the 1st case returns a UAC and QID of type "01"

I'm not sure of the benefit of having it split over 2 steps, and putting more 'stuff' in the context magic