Remove sftp from export service
ONSdigital/ssdc-rm-acceptance-tests pull request #83
Opened 2021-11-18 09:10 UTC by hbrace

# Motivation and Context

* [ ] [Context Index](/CODE_GUIDE.md#context-index) has been kept up to date

We no longer want to use sftp as the place to put export files, instead for now we only want to use GCS buckets

# What has changed

Everything sftp removed, changes made to make writing to GCS buckets more concrete, configurable to use local file system when running locally.

# How to test?

Running locally
1. Build export file service image
3. with `ssdc-rm-docker-dev` on branch of the same name: `make up`
4.`make test` to run the tests

Running locally using real GCS buckets:
1. Follow the new instructions on the export file service to set variables
2. Do the same in the acceptance tests
3. `make test`

Running in GCP
1. Apply terraform to your env from the branch of the same name
1. `make docker_build`
2. In the export file service repo, `docker tag eu.gcr.io/ons-ci-rm/rm/ssdc-rm-export-file-service:latest eu.gcr.io/ssdc-rm-<<YOUR-ENV>>/rm/ssdc-rm-export-file-service:latest
3. `docker push eu.gcr.io/ssdc-rm-<<YOUR-ENV>>/rm/ssdc-rm-export-file-service`
4. Edit export file service manifest file in `ssdc-rm-kubernetes` to use your pushed image and apply this
5.  Build docker image, tag and push the acceptance tests to your env in the same way
6. In acceptance tests directory, edit the `acceptance_tests_pod.yml` to point to your envs AT image
7. `./run_gke`

# Links

https://trello.com/c/tqkddH1D/3019-export-file-service-remove-sftp-just-send-files-to-a-gcs-bucket-or-local-directory-8
# Screenshots (if appropriate):

2021-11-19 09:00 UTC, ryangrundy7 commented on config.py
> +    PLATFORM = os.getenv('PLATFORM', 'LOCAL')
These variables aren't being used anywhere according to vulture?

2021-11-19 09:02 UTC, ryangrundy7 commented on acceptance_tests/features/steps/export_file.py
> +from acceptance_tests.utilities.export_file_helper import get_all_files_after_time, get_files_content_as_list
Doesn't exist anymore?

2021-11-19 09:06 UTC, ryangrundy7 commented on acceptance_tests_pod.yml
> +    image: eu.gcr.io/ssdc-rm-braceh1/rm/ssdc-rm-acceptance-tests:latest
Pointing to your dev env

2021-11-19 09:07 UTC, ryangrundy7 requested changes
Looks like the PR is missing some stuff

2021-11-22 16:03 UTC, ryangrundy7 approved these changes
All tests pass 👍

2021-11-23 13:08 UTC, liamtoozer approved these changes
Looks good. Passes locally for me 👍

2021-11-23 13:57 UTC, merged