3352 split acceptance tests into a lightweight core set and full regression set
ONSdigital/ssdc-rm-acceptance-tests pull request #96
Opened 2022-03-25 12:09 UTC by LukeLoze1

# Motivation and Context
Add regression tags

# What has changed
Added regression tags and new commands etc

# How to test?
Run locally:  make test = run all,  make test_core = run none regression tests only.   Also should show skipped now.

# Links
https://trello.com/c/c9ZR6lt4/3352-split-acceptance-tests-into-a-lightweight-core-set-and-full-regression-set-8

2022-03-25 13:28 UTC, ryangrundy7 approved these changes
Looks good to me 👍

2022-03-28 07:14 UTC, AdamHawtin requested changes
Looks good, just a few small comments on the scripting bits

2022-03-28 07:14 UTC, AdamHawtin commented on run_gke.sh
> +DEFAULT_TAGS = ''
Doesn't look like `DEFAULT_TAGS` is used anywhere?

2022-03-28 07:14 UTC, AdamHawtin commented on tasks/kubectl-run-acceptance-tests.yml
> +      "sleep 2; behave acceptance_tests/features --no-logcapture --logging-level WARN  --tags=~@regression"
I think we should keep `--no-skipped`, otherwise behave logs all the steps it's skipping.

2022-03-28 07:14 UTC, AdamHawtin commented on tasks/kubectl-run-regression-acceptance-tests.yml
> +platform: linux
Could tags be passed into the job as a param, so we only need one task definition?
🎨

2022-03-28 07:14 UTC, AdamHawtin commented on run.py
> -    parser.add_argument('--show_skipped', help='Show skipped tests', action='store_true')
I think we want to keep this, the logs of the non-regression runs get quite busy with all the skipped steps otherwise.

2022-03-31 07:53 UTC, AdamHawtin commented on run.py
> +    args = f'--logging-level {args.log_level} --format {args.format} {args.feature_directory} {tags_arg}'
The `show_skipped` bits here need to be restored

2022-03-31 09:36 UTC, AdamHawtin approved these changes
LGTM 👍

2022-03-31 09:39 UTC, merged